service: discord-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct
  architecture: arm64

functions:
  main:
    handler: src/handler.main
    events:
      - http:
          path: /
          method: POST
          integration: lambda

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
